module.exports = (bot) => {

	bot.guns = {
		knife: {
			id: 1,
			desc: "Faca",
			data: "knife",
			emote: "faca",
			preço: 2500,
			atk: 15,
			def: 0,
			moneyAtk: 6,
			moneyDef: 8,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.açougueiro.desc}\n**Roubar:** ${bot.robbery.velhinha.desc}`
		},
		colt45: {
			id: 2,
			desc: "Colt 45",
			data: "colt45", // arrumar quando resetar
			emote: "colt45",
			preço: 5900,
			atk: 20,
			def: 5,
			moneyAtk: 8,
			moneyDef: 12,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.vigilante.desc}\n**Roubar:** ${bot.robbery.mercearia.desc}`
		},
		tec9: {
			id: 3,
			desc: "Tec 9",
			data: "tec9",
			emote: "tec9",
			preço: 15000,
			atk: 25,
			def: 10,
			moneyAtk: 10,
			moneyDef: 16,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.segurança.desc}\n**Roubar:** ${bot.robbery.posto.desc}`,
		},
		rifle: {
			id: 4,
			desc: "Rifle",
			data: "rifle",
			emote: "rifle",
			preço: 27000,
			atk: 30,
			def: 15,
			moneyAtk: 12,
			moneyDef: 20,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.caçador.desc}\n**Roubar:** ${bot.robbery.posto.desc}`,
		},
		shotgun: {
			id: 5,
			desc: "Escopeta",
			data: "shotgun",
			emote: "escopeta",
			preço: 40000,
			atk: 35,
			def: 20,
			moneyAtk: 14,
			moneyDef: 24,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.funeral.desc}\n**Roubar:** ${bot.robbery.joalheria.desc}\n**Vasculhar:** Fábrica de armas`,
		},
		mp5: {
			id: 6,
			desc: "MP5",
			data: "mp5",
			emote: "mp5",
			preço: 65000,
			atk: 40,
			def: 25,
			moneyAtk: 16,
			moneyDef: 28,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.milicia.desc}\n**Roubar:** ${bot.robbery.joalheria.desc}\n**Vasculhar:** Fábrica de armas`,
		},
		ak47: {
			id: 7,
			desc: "AK-47",
			data: "ak47",
			emote: "ak47",
			preço: 100000,
			atk: 45,
			def: 30,
			moneyAtk: 18,
			moneyDef: 32,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.mercenario.desc}\n**Roubar:** ${bot.robbery.banco.desc}\n**Vasculhar:** Usina nuclear, Fábrica de armas`,
		},
		m4: {
			id: 8,
			desc: "M4",
			data: "m4",
			emote: "m4",
			preço: 135000,
			atk: 50,
			def: 35,
			moneyAtk: 20,
			moneyDef: 36,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.rei.desc}\n**Roubar:** ${bot.robbery.banco.desc}\n**Vasculhar:** Usina nuclear, Fábrica de armas`,
		},
		sniper: {
			id: 9,
			desc: "Sniper",
			data: "sniper",
			emote: "sniper",
			preço: 210000,
			atk: 55,
			def: 40,
			moneyAtk: 22,
			moneyDef: 40,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc} e ${bot.jobs.espiao.desc}\n**Roubar:** ${bot.robbery.banco.desc}\n**Vasculhar:** Usina nuclear, Fábrica de armas`,
		},
		katana: {
			id: 10,
			desc: "Katana",
			data: "katana",
			emote: "katana",
			preço: 330000,
			atk: 60,
			def: 45,
			moneyAtk: 24,
			moneyDef: 44,
			utilidade: `**Trabalho:** ${bot.jobs.duble.desc}, ${bot.jobs.jacobi.desc}, ${bot.jobs.et.desc} e ${bot.jobs.yakuza.desc}\n**Roubar:** ${bot.robbery.mafia.desc}\n**Vasculhar:** Usina nuclear, Fábrica de armas`,
		},
		rpg: {
			id: 11,
			desc: "RPG",
			data: "rpg",
			emote: "rpg",
			preço: 666000,
			atk: 70,
			def: 35,
			moneyAtk: 26,
			moneyDef: 48,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc}, ${bot.jobs.et.desc} e ${bot.jobs.bomba.desc}\n**Roubar:** ${bot.robbery.mafia.desc}\n**Vasculhar:** Nave extraterrestre, Usina nuclear, Fábrica de armas`,
		},
		goggles: {
			id: 12,
			desc: "Óculos Noturno",
			data: "goggles",
			emote: "goggles",
			preço: 300000,
			atk: '+3 (noite)',
			def: '+3 (noite)',
			moneyAtk: null,
			moneyDef: null,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc}, ${bot.jobs.et.desc} e ${bot.jobs.duble.desc}\n Aumenta em 3 o ATK e DEF durante a noite (entre 20h e 4h)`,
		},
		colete: {
			id: 13,
			desc: "Colete Leve",
			data: "colete",
			emote: "colete",
			preço: 175000,
			atk: null,
			def: '+2',
			moneyAtk: null,
			moneyDef: null,
			utilidade: `**Trabalho:** ${bot.jobs.jacobi.desc}e ${bot.jobs.et.desc}\nAumenta em 2 a DEF (pode ser acumulado com outros coletes)`,
		},
		colete_p: {
			id: 14,
			desc: "Colete Pesado",
			data: "colete_p",
			emote: "colete_p",
			preço: 1000000,
			atk: null,
			def: '+5',
			moneyAtk: null,
			moneyDef: null,
			utilidade: `**Trabalho:** ${bot.jobs.et.desc}\nAumenta em 5 a DEF (pode ser acumulado com outros coletes)`,
		},
		celular: {
			id: 15,
			desc: "Celular",
			data: "celular",
			emote: "cellphone",
			preço: 100000,
			atk: null,
			def: null,
			moneyAtk: null,
			moneyDef: null,
			utilidade: null,
		},
		jetpack: {
			id: 16,
			desc: "Jetpack",
			data: "jetpack",
			emote: "jetpack",
			preço: 5000000,
			atk: null,
			def: null,
			moneyAtk: null,
			moneyDef: null,
			utilidade: `**Trabalho:** ${bot.jobs.duble.desc} e ${bot.jobs.conquistador.desc}\n+30% de chance de fuga da prisão`,
		},
		minigun: {
			id: 17,
			desc: "Minigun",
			data: "minigun", // uData._minigun
			emote: "minigun", //bot.config.minigun
			preço: 10000000,
			atk: 80,
			def: 45,
			moneyAtk: 28,
			moneyDef: 52,
			utilidade: `**Trabalho:** ${bot.jobs.mafia.desc}, ${bot.jobs.informante.desc} e ${bot.jobs.conquistador.desc}\n**Roubar**: ${bot.robbery.deposito.desc}\n**Vasculhar:** Base militar, Nave extraterrestre, Usina nuclear, Fábrica de armas`,
		},
		bazuca: {
			id: 18,
			desc: "Bazuca",
			data: "bazuca", // uData._bazuca
			emote: "bazuca", //bot.config.bazuca
			preço: "-",
			atk: 90,
			def: 50,
			moneyAtk: 30,
			moneyDef: 56,
			utilidade: `**Trabalho:** ${bot.jobs.conquistador.desc}\n**Roubar**: ${bot.robbery.palacio.desc}\n**Vasculhar:** Base militar, Nave extraterrestre, Usina nuclear, Fábrica de armas`,
		},
		exoesqueleto: {
			id: 19,
			desc: "Exoesqueleto",
			data: "exoesqueleto", // uData._exoesqueleto
			emote: "exoesqueleto", //bot.config.exoesqueleto
			preço: 20000000,
			atk: null,
			def: '+5',
			moneyAtk: null,
			moneyDef: '+5',
			utilidade: `**Trabalho:** ${bot.jobs.conquistador.desc}\nAumenta em 5 a DEF (pode ser acumulado com coletes) e em 5% o valor defendido`,
		},
		ovogranada: {
			id: 20,
			desc: "Granada",
			data: "ovogranada", // uData._exoesqueleto
			emote: "ovogranada", //bot.config.exoesqueleto
			preço: 750000,
			atk: '+5',
			def: null,
			moneyAtk: null,
			moneyDef: null,
			utilidade: 'Aumenta em 5 o ATK (é consumido ao utilizar) ',
		}
	};
} 